// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/pjoc-team/pay-gateway/pkg/gateway"
	"github.com/pjoc-team/pay-proto/go"
)

// Injectors from wire.go:

func NewPayGateway(clusterID string, concurrency int) (pay.PayGatewayServer, error) {
	configClients, err := InitConfigClients()
	if err != nil {
		return nil, err
	}
	payDatabaseServiceClient, err := InitDbClient()
	if err != nil {
		return nil, err
	}
	payGatewayServer, err := gateway.NewPayGateway(configClients, clusterID, concurrency, payDatabaseServiceClient)
	if err != nil {
		return nil, err
	}
	return payGatewayServer, nil
}

// wire.go:

var set = wire.NewSet(InitConfigClients, InitDbClient)
