// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/google/wire"
	"github.com/pjoc-team/pay-gateway/pkg/configclient"
	"github.com/pjoc-team/pay-gateway/pkg/gateway"
	"github.com/pjoc-team/pay-proto/go"
)

// Injectors from wire.go:

func NewPayGateway(configclients configclient.ConfigClients, clusterID string, concurrency int) (pay.PayGatewayServer, error) {
	payDatabaseServiceClient, err := InitDbClient()
	if err != nil {
		return nil, err
	}
	payGatewayServer, err := gateway.NewPayGateway(configclients, clusterID, concurrency, payDatabaseServiceClient)
	if err != nil {
		return nil, err
	}
	return payGatewayServer, nil
}

// wire.go:

var set = wire.NewSet(InitDbClient)
